name: ViaAprilFools
main: net.raphimc.viaaprilfools.BukkitPlugin
authors: [RK_01, FlorianMichael/EnZaXD]
version: 3.0.2-SNAPSHOT
description: ViaVersion addon to add support for some notable Minecraft snapshots
website: https://viaversion.com/aprilfools
api-version: 1.13
folia-supported: true
load: STARTUP
depend: [ViaVersion, ViaBackwards]