package com.viaversion.viaversion.api.type;

import com.viaversion.viaversion.api.type.types.ArrayType;
import com.viaversion.viaversion.api.type.types.BitSetType;
import com.viaversion.viaversion.api.type.types.BooleanType;
import com.viaversion.viaversion.api.type.types.ByteArrayType;
import com.viaversion.viaversion.api.type.types.ByteType;
import com.viaversion.viaversion.api.type.types.ComponentType;
import com.viaversion.viaversion.api.type.types.DoubleType;
import com.viaversion.viaversion.api.type.types.EmptyType;
import com.viaversion.viaversion.api.type.types.FloatType;
import com.viaversion.viaversion.api.type.types.IntArrayType;
import com.viaversion.viaversion.api.type.types.IntType;
import com.viaversion.viaversion.api.type.types.LongArrayType;
import com.viaversion.viaversion.api.type.types.LongType;
import com.viaversion.viaversion.api.type.types.OptionalVarIntType;
import com.viaversion.viaversion.api.type.types.RegistryEntryType;
import com.viaversion.viaversion.api.type.types.RemainingBytesType;
import com.viaversion.viaversion.api.type.types.ShortByteArrayType;
import com.viaversion.viaversion.api.type.types.ShortType;
import com.viaversion.viaversion.api.type.types.StringType;
import com.viaversion.viaversion.api.type.types.UUIDType;
import com.viaversion.viaversion.api.type.types.UnsignedByteType;
import com.viaversion.viaversion.api.type.types.UnsignedShortType;
import com.viaversion.viaversion.api.type.types.VarIntArrayType;
import com.viaversion.viaversion.api.type.types.VarIntType;
import com.viaversion.viaversion.api.type.types.VarLongType;
import com.viaversion.viaversion.api.type.types.block.BlockChangeRecordType;
import com.viaversion.viaversion.api.type.types.block.BlockEntityType1_18;
import com.viaversion.viaversion.api.type.types.block.BlockEntityType1_20_2;
import com.viaversion.viaversion.api.type.types.block.VarLongBlockChangeRecordType;
import com.viaversion.viaversion.api.type.types.item.ItemShortArrayType1_13;
import com.viaversion.viaversion.api.type.types.item.ItemShortArrayType1_13_2;
import com.viaversion.viaversion.api.type.types.item.ItemShortArrayType1_8;
import com.viaversion.viaversion.api.type.types.item.ItemType1_13;
import com.viaversion.viaversion.api.type.types.item.ItemType1_13_2;
import com.viaversion.viaversion.api.type.types.item.ItemType1_20_2;
import com.viaversion.viaversion.api.type.types.item.ItemType1_8;
import com.viaversion.viaversion.api.type.types.math.BlockPositionType1_14;
import com.viaversion.viaversion.api.type.types.math.BlockPositionType1_8;
import com.viaversion.viaversion.api.type.types.math.ChunkPositionType;
import com.viaversion.viaversion.api.type.types.math.EulerAngleType;
import com.viaversion.viaversion.api.type.types.math.GlobalBlockPositionType;
import com.viaversion.viaversion.api.type.types.math.QuaternionType;
import com.viaversion.viaversion.api.type.types.math.Vector3fType;
import com.viaversion.viaversion.api.type.types.math.VectorType;
import com.viaversion.viaversion.api.type.types.misc.CompoundTagType;
import com.viaversion.viaversion.api.type.types.misc.GameProfileType;
import com.viaversion.viaversion.api.type.types.misc.HolderSetType;
import com.viaversion.viaversion.api.type.types.misc.HolderType;
import com.viaversion.viaversion.api.type.types.misc.NamedCompoundTagType;
import com.viaversion.viaversion.api.type.types.misc.PlayerMessageSignatureType;
import com.viaversion.viaversion.api.type.types.misc.ProfileKeyType;
import com.viaversion.viaversion.api.type.types.misc.SoundEventType;
import com.viaversion.viaversion.api.type.types.misc.TagType;
import com.viaversion.viaversion.api.type.types.misc.VillagerDataType;

public final class Types {
   public static final Type EMPTY = new EmptyType();
   public static final ByteType BYTE = new ByteType();
   public static final UnsignedByteType UNSIGNED_BYTE = new UnsignedByteType();
   public static final Type BYTE_ARRAY_PRIMITIVE = new ByteArrayType();
   public static final Type OPTIONAL_BYTE_ARRAY_PRIMITIVE = new ByteArrayType.OptionalByteArrayType();
   public static final Type SHORT_BYTE_ARRAY = new ShortByteArrayType();
   public static final Type REMAINING_BYTES = new RemainingBytesType();
   public static final Type INT_ARRAY_PRIMITIVE = new IntArrayType();
   public static final ShortType SHORT = new ShortType();
   public static final UnsignedShortType UNSIGNED_SHORT = new UnsignedShortType();
   public static final IntType INT = new IntType();
   public static final FloatType FLOAT = new FloatType();
   public static final FloatType.OptionalFloatType OPTIONAL_FLOAT = new FloatType.OptionalFloatType();
   public static final DoubleType DOUBLE = new DoubleType();
   public static final LongType LONG = new LongType();
   public static final Type LONG_ARRAY_PRIMITIVE = new LongArrayType();
   public static final BooleanType BOOLEAN = new BooleanType();
   public static final BooleanType.OptionalBooleanType OPTIONAL_BOOLEAN = new BooleanType.OptionalBooleanType();
   public static final Type COMPONENT = new ComponentType();
   public static final Type OPTIONAL_COMPONENT = new ComponentType.OptionalComponentType();
   public static final Type STRING = new StringType();
   public static final Type OPTIONAL_STRING = new StringType.OptionalStringType();
   public static final Type STRING_ARRAY;
   public static final Type UUID;
   public static final Type OPTIONAL_UUID;
   public static final Type UUID_ARRAY;
   public static final VarIntType VAR_INT;
   public static final OptionalVarIntType OPTIONAL_VAR_INT;
   public static final Type VAR_INT_ARRAY_PRIMITIVE;
   public static final VarLongType VAR_LONG;
   public static final Type BLOCK_POSITION1_8;
   public static final Type OPTIONAL_POSITION1_8;
   public static final Type BLOCK_POSITION1_14;
   public static final Type OPTIONAL_POSITION_1_14;
   public static final Type ROTATIONS;
   public static final Type VECTOR;
   public static final Type VECTOR3F;
   public static final Type QUATERNION;
   public static final Type NAMED_COMPOUND_TAG;
   public static final Type OPTIONAL_NAMED_COMPOUND_TAG;
   public static final Type NAMED_COMPOUND_TAG_ARRAY;
   public static final Type COMPOUND_TAG;
   public static final Type OPTIONAL_COMPOUND_TAG;
   public static final Type TAG;
   public static final Type TAG_ARRAY;
   public static final Type OPTIONAL_TAG;
   public static final Type GLOBAL_POSITION;
   public static final Type OPTIONAL_GLOBAL_POSITION;
   public static final Type CHUNK_POSITION;
   public static final Type BLOCK_ENTITY1_18;
   public static final Type BLOCK_ENTITY1_20_2;
   public static final Type BLOCK_CHANGE;
   public static final Type BLOCK_CHANGE_ARRAY;
   public static final Type VAR_LONG_BLOCK_CHANGE;
   public static final Type VAR_LONG_BLOCK_CHANGE_ARRAY;
   public static final Type VILLAGER_DATA;
   public static final Type GAME_PROFILE;
   public static final Type PROFILE_KEY;
   public static final Type OPTIONAL_PROFILE_KEY;
   public static final Type PLAYER_MESSAGE_SIGNATURE;
   public static final Type OPTIONAL_PLAYER_MESSAGE_SIGNATURE;
   public static final Type PLAYER_MESSAGE_SIGNATURE_ARRAY;
   public static final BitSetType PROFILE_ACTIONS_ENUM;
   public static final ByteArrayType SIGNATURE_BYTES;
   public static final BitSetType ACKNOWLEDGED_BIT_SET;
   public static final ByteArrayType.OptionalByteArrayType OPTIONAL_SIGNATURE_BYTES;
   public static final Type REGISTRY_ENTRY;
   public static final Type REGISTRY_ENTRY_ARRAY;
   public static final Type HOLDER_SET;
   public static final Type OPTIONAL_HOLDER_SET;
   public static final HolderType SOUND_EVENT;
   public static final Type ITEM1_8;
   public static final Type ITEM1_13;
   public static final Type ITEM1_13_2;
   public static final Type ITEM1_20_2;
   public static final Type ITEM1_8_SHORT_ARRAY;
   public static final Type ITEM1_13_SHORT_ARRAY;
   public static final Type ITEM1_13_2_SHORT_ARRAY;
   public static final Type ITEM1_13_ARRAY;
   public static final Type ITEM1_13_2_ARRAY;
   public static final Type ITEM1_20_2_ARRAY;

   static {
      STRING_ARRAY = new ArrayType(STRING);
      UUID = new UUIDType();
      OPTIONAL_UUID = new UUIDType.OptionalUUIDType();
      UUID_ARRAY = new ArrayType(UUID);
      VAR_INT = new VarIntType();
      OPTIONAL_VAR_INT = new OptionalVarIntType();
      VAR_INT_ARRAY_PRIMITIVE = new VarIntArrayType();
      VAR_LONG = new VarLongType();
      BLOCK_POSITION1_8 = new BlockPositionType1_8();
      OPTIONAL_POSITION1_8 = new BlockPositionType1_8.OptionalBlockPositionType();
      BLOCK_POSITION1_14 = new BlockPositionType1_14();
      OPTIONAL_POSITION_1_14 = new BlockPositionType1_14.OptionalBlockPositionType();
      ROTATIONS = new EulerAngleType();
      VECTOR = new VectorType();
      VECTOR3F = new Vector3fType();
      QUATERNION = new QuaternionType();
      NAMED_COMPOUND_TAG = new NamedCompoundTagType();
      OPTIONAL_NAMED_COMPOUND_TAG = new NamedCompoundTagType.OptionalNamedCompoundTagType();
      NAMED_COMPOUND_TAG_ARRAY = new ArrayType(NAMED_COMPOUND_TAG);
      COMPOUND_TAG = new CompoundTagType();
      OPTIONAL_COMPOUND_TAG = new CompoundTagType.OptionalCompoundTagType();
      TAG = new TagType();
      TAG_ARRAY = new ArrayType(TAG);
      OPTIONAL_TAG = new TagType.OptionalTagType();
      GLOBAL_POSITION = new GlobalBlockPositionType();
      OPTIONAL_GLOBAL_POSITION = new GlobalBlockPositionType.OptionalGlobalPositionType();
      CHUNK_POSITION = new ChunkPositionType();
      BLOCK_ENTITY1_18 = new BlockEntityType1_18();
      BLOCK_ENTITY1_20_2 = new BlockEntityType1_20_2();
      BLOCK_CHANGE = new BlockChangeRecordType();
      BLOCK_CHANGE_ARRAY = new ArrayType(BLOCK_CHANGE);
      VAR_LONG_BLOCK_CHANGE = new VarLongBlockChangeRecordType();
      VAR_LONG_BLOCK_CHANGE_ARRAY = new ArrayType(VAR_LONG_BLOCK_CHANGE);
      VILLAGER_DATA = new VillagerDataType();
      GAME_PROFILE = new GameProfileType();
      PROFILE_KEY = new ProfileKeyType();
      OPTIONAL_PROFILE_KEY = new ProfileKeyType.OptionalProfileKeyType();
      PLAYER_MESSAGE_SIGNATURE = new PlayerMessageSignatureType();
      OPTIONAL_PLAYER_MESSAGE_SIGNATURE = new PlayerMessageSignatureType.OptionalPlayerMessageSignatureType();
      PLAYER_MESSAGE_SIGNATURE_ARRAY = new ArrayType(PLAYER_MESSAGE_SIGNATURE);
      PROFILE_ACTIONS_ENUM = new BitSetType(6);
      SIGNATURE_BYTES = new ByteArrayType(256);
      ACKNOWLEDGED_BIT_SET = new BitSetType(20);
      OPTIONAL_SIGNATURE_BYTES = new ByteArrayType.OptionalByteArrayType(256);
      REGISTRY_ENTRY = new RegistryEntryType();
      REGISTRY_ENTRY_ARRAY = new ArrayType(REGISTRY_ENTRY);
      HOLDER_SET = new HolderSetType();
      OPTIONAL_HOLDER_SET = new HolderSetType.OptionalHolderSetType();
      SOUND_EVENT = new SoundEventType();
      ITEM1_8 = new ItemType1_8();
      ITEM1_13 = new ItemType1_13();
      ITEM1_13_2 = new ItemType1_13_2();
      ITEM1_20_2 = new ItemType1_20_2();
      ITEM1_8_SHORT_ARRAY = new ItemShortArrayType1_8();
      ITEM1_13_SHORT_ARRAY = new ItemShortArrayType1_13();
      ITEM1_13_2_SHORT_ARRAY = new ItemShortArrayType1_13_2();
      ITEM1_13_ARRAY = new ArrayType(ITEM1_13);
      ITEM1_13_2_ARRAY = new ArrayType(ITEM1_13_2);
      ITEM1_20_2_ARRAY = new ArrayType(ITEM1_20_2);
   }
}
